---
title: "Truffle Farm"
author: "A G"
date: "5/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r truffle species}
#Tuber melanosporum
install.packages("dismo")
library("dismo")

 
tuber <- gbif('Tuber', 'melanosporum', sp=TRUE)
plot(tuber)


tuber1<-as.data.frame(tuber)

tuber2<-cbind(tuber1$lon, tuber1$lat)
tuber2<-as.data.frame(tuber2)
head(tuber2)

names(tuber2) <- c("lon", "lat")
head(tuber2)
time<-dim(tuber2)[1]
species<-rep("tuber", time )


tuber2$species<-species

tuber2$species

head(tuber2)

tuber3<-cbind(tuber1$lon, tuber1$lat)

bb_tuber<-bbox(tuber3)

```

```{r}
library(raster)
library(sp)
#get bioclim data 1-19
r <- getData("worldclim",var="bio", res=10) 
plot(r$bio1)

```


```{r}

tuber_crop <- crop(r, bb_tuber)
plot(tuber_crop, main = "Cropped Tuber")


```

```{r}
dir.create('~/MaxEnt_truffle')
```


```{r}
library(dismo)

# Randomly sample 10,000 background points from one background extent raster (only one per cell without replacement). Note: Since the raster has <10,000 pixels, you'll get a warning and all pixels will be used for background. We will be sampling from the biome variable because it is missing some grid cells, and we are trying to avoid getting background points with NA.
bg <- randomPoints(tuber_crop[[12]], n=10000)
bg <- as.data.frame(bg)

#install.packages("spocc")
library(spocc)

#install.packages("ENMeval")
library("ENMeval")

library(rJava)
.jinit()
javaImport(packages = "java.util")

tuber
eval2.tuber <- ENMevaluate(tuber3, tuber_crop, bg, method='checkerboard2', RMvalues=c(1,2), fc=c('L','LQ','LQP'), parallel=TRUE, algorithm='maxent.jar')


### See table of evaluation metrics
eval2.tuber@results

tuber_raster<- eval2.tuber@predictions[[which (eval2.tuber@results$delta.AICc == 0) ]]
tuber_raster
writeRaster(tuber_raster, filename='tuber_raster', format="ascii", overwrite=TRUE)

plot(eval2.tuber@predictions[[which (eval2.tuber@results$delta.AICc == 0) ]])


dev.copy(png,'tuber_maxent.png')
dev.off()


```


```{r sp1 variable importance}
#25 vars
aic.opt <- eval2.tuber@models[[which(eval2.tuber@results$delta.AICc == 0)]]

aic.opt


var.importance(aic.opt)

aic.opt@lambdas

df <- var.importance(aic.opt)
barplot(df$permutation.importance, names.arg=df$variable, las=2, ylab="Permutation Importance")
dev.copy(png,'tuber_importance.png')
dev.off()
#bio6, temperature of the coldest month in most important
```

```{r}
rasValue=extract(r, tuber3)
tuber4<-as.data.frame(tuber3)
names(tuber4) <-c("lon","lat")
head(tuber4)

tuber_envi=cbind(tuber4,rasValue)
head(tuber_envi)
#write.table(combinePointValue,file="combinedPointValue.csv", append=FALSE, sep= ",", row.names = FALSE, col.names=TRUE)

k2 <- kmeans(tuber_envi, centers = 2, nstart = 25)
(k2)

tuber_ecotypes<-cbind(k2$cluster,tuber_envi)
tuber_ecotypes

library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
install.packages("factoextra")
library("factoextra") # clustering algorithms & visualization

fviz_cluster(k2, data = tuber_ecotypes)
k2$centers
library(ggplot2)

map_world <- borders(database = "world", colour = "grey50", fill = "white")  # We used the `Colour Picker` Addin to pick the colours

ggplot() + map_world +  # Plot the map
  geom_point(data = tuber_ecotypes,  # Specify the data for geom_point()
             aes(x = tuber_ecotypes$lon,  # Specify the x axis as longitude
                 y = tuber_ecotypes$lat,  # Specify the y axis as latitude
                 colour = tuber_ecotypes$`k2$cluster`),  # Colour the points based on species name
             alpha = 1,  # Set point opacity to 40%
             size = 2)  +   
  theme(legend.position = "bottom",  # Move the legend to below the plot
        legend.title = element_blank())  # Remove the legend title



tuber_ecotypes

#there are 2 main ecotypes. some occur in France

```
```{r}
install.packages("sf")
library(sf)
install.packages("mapview")
library(mapview)
locations_sf <- st_as_sf(tuber_ecotypes, coords = c("lon", "lat"), crs = 4326)

mapview(locations_sf)
revgeo(longitude=tuber_ecotypes$lon, latitude=tuber_ecotypes$lat, provider = 'photon', output="frame")

```
